// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL || "https://jzuoawqxqmrsftbtjkzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dW9hd3F4cW1yc2Z0YnRqa3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjYwMDcsImV4cCI6MjA2OTk0MjAwN30.iOvn3b02CX_Dch4bWlJbzY6EYLbWrmwpM7sQgAqimd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Prefer browser storage when available; fall back gracefully in non-DOM contexts
const storage = typeof window !== 'undefined' && typeof window.localStorage !== 'undefined'
  ? window.localStorage
  : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  }
});